### ISSUE TITLE
Got this error while trying to crack a hash

### ISSUE THREAD

**Issue by Shubhankitmishra** [UltimateHackers/sqlmate#13]
![screenshot_2](https://user-images.githubusercontent.com/36031123/45811898-f8a99580-bceb-11e8-9f24-37726afa8f57.png)

**Comment by anpseftis** [comment]
Looks like the url isnt complete.

**Comment by Shubhankitmishra** [comment]
@anpseftis  URL ? i am cracking a hash .

**Comment by s0md3v** [comment]
I have kind of abandoned this project but I will fix the bug in free time.
Meanwhile, you can take a look at my [Hash-Buster](https://github.con/s0md3v/Hash-Buster) to do the same job (and more).

**Comment by Shubhankitmishra** [comment]
Yeah, I checked the hash-buster it's nice. but for me :(
![image](https://user-images.githubusercontent.com/36031123/45821458-e426c680-bd06-11e8-9834-426d996c6fd0.png)

**Comment by s0md3v** [comment]
This isn't Hash Buster's fault. It looked up your hash in 4 different databases and none of them had it.

**Comment by Shubhankitmishra** [comment]
Okay.. You should change hash-buster's description to "Find Hashes in seconds".
thanks.
[EDITED] "FIND PLAIN TEXT OF ENCODED STRINGS IN SECONDS" looks good. :100:

**Comment by s0md3v** [comment]
> Okay.. You should change hash-buster's description to "Find Hashes in seconds".

It finds plaintext for hashes not hashes :laughing:

**Comment by s0md3v** [comment]
> [EDITED] "FIND PLAIN TEXT OF ENCODED STRINGS IN SECONDS" looks good. 100

Encoding and hashing are two totally different things :')

**Comment by Shubhankitmishra** [comment]
Crack hashes in seconds. is ok :+1:  i lost.
is it possible to crack a md5 encrpted string?

**Comment by keyunlocker12** [comment]
@s0md3v This what I get when trying to run the program after installing: 

root@debian:/home/tanaka/Desktop/sqlmate-master# pip install -r requirements.txt
Requirement already satisfied: mechanize==0.2.5 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (0.2.5)
Requirement already satisfied: beautifulsoup4==4.4.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (4.4.1)
Requirement already satisfied: argparse==1.2.1 in /usr/lib/python2.7 (from -r requirements.txt (line 3)) (1.2.1)
Requirement already satisfied: requests==2.9.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (2.9.1)
root@debian:/home/tanaka/Desktop/sqlmate-master# python sqlmate
Traceback (most recent call last):
  File "sqlmate", line 4, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
root@debian:/home/tanaka/Desktop/sqlmate-master#

What should I do please?

**Comment by keyunlocker12** [comment]
@s0md3v There are some website I can't find their Admin page login ...I tried so many tools. don't know if they have other site to login access... their website is up and running but the admin login page can't be found ...please help.

**Comment by Shubhankitmishra** [comment]
> @s0md3v There are some website I can't find their Admin page login ...I tried so many tools. don't know if they have other site to login access... their website is up and running but the admin login page can't be found ...please help.

If target website is running on apache web-server then try this one...https://github.com/mIcHyAmRaNe/okadminfinder3

**Comment by himeshvyas26** [comment]
pip install beautifulsoup4

use this command if any error occurre like this

File "sqlmate", line 4, in 
from bs4 import BeautifulSoup
File "/usr/local/lib/python2.7/dist-packages/bs4/init.py", line 30, in 
from .builder import builder_registry, ParserRejectedMarkup
