### ISSUE TITLE
Fresh install on Ubuntu 16.04 VPS

### ISSUE THREAD

**Issue by georgeglarson** [UltimateHackers/sqlmate#5]
Notes from doing an install on a fresh Ubuntu 16.04 VPS:

1. pip wasn't installed:
    * apt install python-pip

2. lxml wasn't installed:
    * pip install lxml

```
Traceback (most recent call last):
  File "sqlmate", line 367, in <module>
    bypass()
  File "sqlmate", line 266, in bypass
    soup =  BeautifulSoup(data, 'lxml') #Pareses the response with beuatiful soup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 156, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

3. no control matching 'username'
    * haven't worked in Python extensively or recently 
    * seems that we passed "if username:" but then failed for missing control
        * perhaps something failed to load?  could not reproduce in pdb
```
Traceback (most recent call last):
  File "sqlmate", line 367, in <module>
    bypass()
  File "sqlmate", line 271, in bypass
    find(url, i_title, original)
  File "sqlmate", line 226, in find
    brute(username, passwd, menu, option, name, form_number, i_title, original) #Calls the bruteforce function
  File "sqlmate", line 234, in brute
    br.form[username] = "'or' '='"
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_form.py", line 2780, in __setitem__
    control = self.find_control(name)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_form.py", line 3101, in find_control
    return self._find_control(name, type, kind, id, label, predicate, nr)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_form.py", line 3185, in _find_control
    raise ControlNotFoundError("no control matching "+description)
mechanize._form.ControlNotFoundError: no control matching name 'username'
```

**Comment by s0md3v** [comment]
1. Really man? Do you expect it to run without any libraries?
2. Sorry I forgot to mention that in requirements.txt
3. Alright I will fix that

**Comment by georgeglarson** [comment]
LOLs.  No, of course I didn't expect it to run without libraries. =D

My experience is that new users will often give up if something doesn't work immediately.  Since I was running on a fresh install, I figured that posting the error messages to the Github would cause it to show up in search engines if someone pasted in the error that they received.
