### ISSUE TITLE
error when i run python sqlmate 

### ISSUE THREAD

**Issue by getsecnow** [UltimateHackers/sqlmate#7]
Traceback (most recent call last):
  File "sqlmate", line 4, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):

**Comment by UltimateHackers** [comment]
You can resolve this issue by entering the following commands in terminal:
`pip install --upgrade beautifulsoup4
pip install --upgrade html5lib`
PS: This issue is caused by outdated libraries and is not a bug in sqlmate

**Comment by UltimateHackers** [comment]
Closing this issue due to inactivity.

**Comment by dmar123** [comment]
Dude Im in Love with u !?

**Comment by UltimateHackers** [comment]
@dmar123 lol what?
